// <auto-generated />
using System;
using FirstRestfulAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstRestfulAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240605174701_Seeding Data for Difficulties and Regions")]
    partial class SeedingDataforDifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstRestfulAPI.Model.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e40053c1-b804-4c40-95c1-8fc321291e8e"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("f6aea21c-22c4-4da7-bbdb-46a36f230115"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("b9c2ce9d-f7c6-4a15-9436-9c8a8318777a"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("FirstRestfulAPI.Model.Domain.Region", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            id = new Guid("152b9ea2-3e52-46e4-b60e-2c13236c3848"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "img.jpg"
                        },
                        new
                        {
                            id = new Guid("25e1acd0-ddde-4b01-9a83-2ebd4330a52c"),
                            Code = "BNG",
                            Name = "Bangladesh",
                            RegionImageUrl = "img.jpg"
                        },
                        new
                        {
                            id = new Guid("5262e70b-5aa5-440c-bac2-2b219fb63325"),
                            Code = "PAK",
                            Name = "Pakistan",
                            RegionImageUrl = "img.jpg"
                        });
                });

            modelBuilder.Entity("FirstRestfulAPI.Model.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("FirstRestfulAPI.Model.Domain.Walk", b =>
                {
                    b.HasOne("FirstRestfulAPI.Model.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstRestfulAPI.Model.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
